version: "3.8"
services:
  # Database
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FizzBuzzGame
    ports:
      - "5444:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]

  # Backend API (.NET 8)
  backend:
    build:
      context: ./BackEnd/WebApplication1
      dockerfile: Dockerfile
    container_name: fizzbuzz-backend
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=FizzBuzzGame;Username=postgres;Password=postgres"
      ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Frontend (Next.js)
  frontend:
    build:
      context: ./FrontEnd/my-app
      dockerfile: Dockerfile
    container_name: fizzbuzz-frontend
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_URL: "http://backend:8080"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend

# Named volumes for data persistence
volumes:
  db-data:
